FROM {image}

RUN apk upgrade --update && \
    apk add --no-cache make bash build-base cmake python3 git automake autoconf

ENV TAG {tag}
ENV BUILD_TYPE {buildType}

COPY install.sh .
RUN ./install.sh
